version: 0.1.0.{build}
platform: Any CPU
configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
before_build:
  nuget restore src/NotDeadYet.sln
  
build:
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
  project: src/NotDeadYet.sln
  
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
  
test:
  assemblies:
    only:
      - '**/*test*.dll'
      
deploy:
  provider: NuGet
  server: https://www.myget.org/F/not-dead-yet/api/v2/package
  symbol_server: https://www.myget.org/F/not-dead-yet/api/v2/package
  artifact: /.*\.nupkg/
  api_key:
    secure: +9AO8nBsAQL81Ysd57P8JaREcHlNvAONVdCtaPKfBLBryOPIlctFe/NA7MJPj08Q
  skip_symbols: false
