version: 0.1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  nuget restore src/NotDeadYet.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
  project: src/NotDeadYet.sln
test:
  assemblies:
    only:
      - '**/*test*.dll'
deploy:
  provider: NuGet
  server: https://www.myget.org/F/not-dead-yet/api/v2/package
  api_key:
    secure: +9AO8nBsAQL81Ysd57P8JaREcHlNvAONVdCtaPKfBLBryOPIlctFe/NA7MJPj08Q
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.symbols\.nupkg/
